In [ ]:
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

countries_nona = pd.read_csv("test_model_df.csv")

In [ ]:
countries_df_nona.columns[36]
X = countries_df_nona.drop(countries_df_nona.columns[36], axis = 1)

# ['Country', 'Abbreviation', 'Capital/Major City', 'Largest city', 'Official language', 'Country Code', 'Region', 'Level', 'Countrycode', 'Region_2015', 'Standard Error', ]

In [ ]:
X = X.drop(X.columns[48:91], axis = 1)

In [ ]:
X = X.drop(['Country', 'Abbreviation', 'Capital/Major City', 'Largest city', 'Official language', 'Country Code', 'Region', 'Level', 'Countrycode'], axis = 1)

In [ ]:
X = X.drop(['Currency-Code'], axis = 1)

In [ ]:
X.describe(include = "all")

,Density\n(P/Km2),Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Co2-Emissions,CPI,CPI Change (%),Fertility Rate,...,Hindus,Jews,Other_religions,Happiness Score_2019,Economy (GDP per Capita)_2019,Social support_2019,Health (Life Expectancy)_2019,Freedom_2019,Generosity_2019,Trust (Government Corruption)_2019
count,95,95,95,95,95.000000,95.000000,95,95,95,95.000000,...,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
unique,78,90,95,76,NaN,NaN,95,95,58,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,83,64.80%,"652,230","9,000",NaN,NaN,"8,672",149.9,0.70%,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3,2,1,4,NaN,NaN,1,1,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,19.330316,333.147368,NaN,NaN,NaN,2.552526,...,2.742472,0.913906,1.658015,5.425589,0.923505,1.211716,0.744484,0.389621,0.175800,0.091211
std,NaN,NaN,NaN,NaN,9.725668,347.821945,NaN,NaN,NaN,1.247711,...,12.644703,8.048507,2.806924,0.989631,0.342559,0.285153,0.209186,0.131460,0.101485,0.072873
min,NaN,NaN,NaN,NaN,6.400000,1.000000,NaN,NaN,NaN,0.980000,...,0.000000,0.000000,0.000000,3.203000,0.138000,0.378000,0.232000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,10.900000,63.500000,NaN,NaN,NaN,1.625000,...,0.001347,0.000254,0.114118,4.654500,0.681000,1.057000,0.584500,0.310000,0.101000,0.040500
50%,NaN,NaN,NaN,NaN,17.550000,232.000000,NaN,NaN,NaN,2.090000,...,0.009422,0.007316,0.592142,5.425000,1.002000,1.269000,0.808000,0.418000,0.166000,0.078000
75%,NaN,NaN,NaN,NaN,24.690000,383.000000,NaN,NaN,NaN,3.055000,...,0.098409,0.047699,2.021979,6.111500,1.185000,1.446500,0.874000,0.495000,0.239500,0.113500
max,NaN,NaN,NaN,NaN,46.080000,1876.000000,NaN,NaN,NaN,6.910000,...,81.522942,78.499756,17.799625,7.307000,1.609000,1.557000,1.062000,0.585000,0.566000,0.380000

In [ ]:
X.loc[:, 'Density\n(P/Km2)'] = X['Density\n(P/Km2)'].apply(strnum_to_int)
X.loc[:, 'Land Area(Km2)'] = X['Land Area(Km2)'].apply(strnum_to_int)
X.loc[:, 'Armed Forces size'] = X['Armed Forces size'].apply(strnum_to_int)
X.loc[:, 'Co2-Emissions'] = X['Co2-Emissions'].apply(strnum_to_int)

In [ ]:
X.describe(include = 'all')

,Density\n(P/Km2),Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Co2-Emissions,CPI,CPI Change (%),Fertility Rate,...,Hindus,Jews,Other_religions,Happiness Score_2019,Economy (GDP per Capita)_2019,Social support_2019,Health (Life Expectancy)_2019,Freedom_2019,Generosity_2019,Trust (Government Corruption)_2019
count,95,95,95,95,95.000000,95.000000,95,95,95,95.000000,...,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
unique,78,90,95,76,NaN,NaN,95,95,58,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,83,64.80%,652230,9000,NaN,NaN,8672,149.9,0.70%,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3,2,1,4,NaN,NaN,1,1,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,19.330316,333.147368,NaN,NaN,NaN,2.552526,...,2.742472,0.913906,1.658015,5.425589,0.923505,1.211716,0.744484,0.389621,0.175800,0.091211
std,NaN,NaN,NaN,NaN,9.725668,347.821945,NaN,NaN,NaN,1.247711,...,12.644703,8.048507,2.806924,0.989631,0.342559,0.285153,0.209186,0.131460,0.101485,0.072873
min,NaN,NaN,NaN,NaN,6.400000,1.000000,NaN,NaN,NaN,0.980000,...,0.000000,0.000000,0.000000,3.203000,0.138000,0.378000,0.232000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,10.900000,63.500000,NaN,NaN,NaN,1.625000,...,0.001347,0.000254,0.114118,4.654500,0.681000,1.057000,0.584500,0.310000,0.101000,0.040500
50%,NaN,NaN,NaN,NaN,17.550000,232.000000,NaN,NaN,NaN,2.090000,...,0.009422,0.007316,0.592142,5.425000,1.002000,1.269000,0.808000,0.418000,0.166000,0.078000
75%,NaN,NaN,NaN,NaN,24.690000,383.000000,NaN,NaN,NaN,3.055000,...,0.098409,0.047699,2.021979,6.111500,1.185000,1.446500,0.874000,0.495000,0.239500,0.113500
max,NaN,NaN,NaN,NaN,46.080000,1876.000000,NaN,NaN,NaN,6.910000,...,81.522942,78.499756,17.799625,7.307000,1.609000,1.557000,1.062000,0.585000,0.566000,0.380000

In [ ]:
y = countries_df_nona[["NetMigSince1960"]]
y.head()
X.dropna(how = "all").shape()

In [ ]:
X_num = X.select_dtypes(include = np.number)

In [ ]:
lm_model = LinearRegression()
lm_model.fit(X_num, y)
y_pred = lm_model.predict(X_num)
r2_score(y, y_pred)

lm_model.coef_
names_list = list(X_num.columns)
coef_list = lm_model.coef_

list(coef_list)
lm_coef = pd.DataFrame({'names': list(X_num.columns), 'coef': lm_model.coef_.ravel().tolist()})

lm_coef

In [ ]:
lm_model.rank_

In [ ]:
X.describe(include = 'all')

,Density\n(P/Km2),Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Co2-Emissions,CPI,CPI Change (%),Fertility Rate,...,Hindus,Jews,Other_religions,Happiness Score_2019,Economy (GDP per Capita)_2019,Social support_2019,Health (Life Expectancy)_2019,Freedom_2019,Generosity_2019,Trust (Government Corruption)_2019
count,95,95,95,95,95.000000,95.000000,95,95,95,95.000000,...,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
unique,78,90,95,76,NaN,NaN,95,95,58,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,83,64.80%,652230,9000,NaN,NaN,8672,149.9,0.70%,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3,2,1,4,NaN,NaN,1,1,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,19.330316,333.147368,NaN,NaN,NaN,2.552526,...,2.742472,0.913906,1.658015,5.425589,0.923505,1.211716,0.744484,0.389621,0.175800,0.091211
std,NaN,NaN,NaN,NaN,9.725668,347.821945,NaN,NaN,NaN,1.247711,...,12.644703,8.048507,2.806924,0.989631,0.342559,0.285153,0.209186,0.131460,0.101485,0.072873
min,NaN,NaN,NaN,NaN,6.400000,1.000000,NaN,NaN,NaN,0.980000,...,0.000000,0.000000,0.000000,3.203000,0.138000,0.378000,0.232000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,10.900000,63.500000,NaN,NaN,NaN,1.625000,...,0.001347,0.000254,0.114118,4.654500,0.681000,1.057000,0.584500,0.310000,0.101000,0.040500
50%,NaN,NaN,NaN,NaN,17.550000,232.000000,NaN,NaN,NaN,2.090000,...,0.009422,0.007316,0.592142,5.425000,1.002000,1.269000,0.808000,0.418000,0.166000,0.078000
75%,NaN,NaN,NaN,NaN,24.690000,383.000000,NaN,NaN,NaN,3.055000,...,0.098409,0.047699,2.021979,6.111500,1.185000,1.446500,0.874000,0.495000,0.239500,0.113500
max,NaN,NaN,NaN,NaN,46.080000,1876.000000,NaN,NaN,NaN,6.910000,...,81.522942,78.499756,17.799625,7.307000,1.609000,1.557000,1.062000,0.585000,0.566000,0.380000